package com.morningsidevc.dao;

import com.morningsidevc.vo.DescBean;
import com.morningsidevc.vo.DescBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DescBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int countByExample(DescBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int deleteByExample(DescBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int insert(DescBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int insertSelective(DescBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    List<DescBean> selectByExample(DescBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    DescBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") DescBean record, @Param("example") DescBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int updateByExample(@Param("record") DescBean record, @Param("example") DescBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int updateByPrimaryKeySelective(DescBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    int updateByPrimaryKey(DescBean record);
}