package com.morningsidevc.vo;

public class DescBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desc.id
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desc.desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column desc.id
     *
     * @return the value of desc.id
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column desc.id
     *
     * @param id the value for desc.id
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column desc.desc
     *
     * @return the value of desc.desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column desc.desc
     *
     * @param desc the value for desc.desc
     *
     * @mbggenerated Tue Jun 23 23:11:25 CST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}